### ISSUE TITLE
Non-empty TDigest

### ISSUE THREAD

**Issue by maoe** [futurice/haskell-tdigest#12]
Does it make sense to implement an API for non-empty `TDigest` so `quantile` returns a plain `Double` rather than `Maybe Double`, and `(minimum|maximum)Value` never return infinity?

The non-empty `TDigest` wouldn't have the Monoid instance and also `tdigest` would look like either of
* `tdigest :: (KnownNat comp) => NonEmpty Double -> TDigest comp` or
* `tdigest :: (Foldable f, KnownNat comp) => f Double -> Maybe (TDigest comp)`.

**Comment by phadej** [comment]
I wouldn't change the current interface for now. Adding `Data.TDigest.NonEmpty` makes sense (and refactoring `Postprocess` to be re-usable for both).

**Comment by phadej** [comment]
this exists in 0.1

**Comment by maoe** [comment]
Thank you!
