### ISSUE TITLE
semigroupoids-6 not allowed

### ISSUE THREAD

**Issue by ysangkok** [futurice/haskell-tdigest#44]
It works with allow-newer, so a revision might be sufficient. This is dependency of servant, which is how I stumbled upon this.

**Comment by phadej** [comment]
Dependency of `servant`?

**Comment by phadej** [comment]
Looks like it's a dependency of `servant-client` test-suite. Why on Earth?

**Comment by ysangkok** [comment]
I saw it in the test suite of `servant-http-streams`: https://hackage.haskell.org/package/servant-http-streams-0.18.4/servant-http-streams.cabal

**Comment by phadej** [comment]
I'll get to updating `tdigest` at some point, its other dependencies are also need bumps. but I'm still puzzled why `servant`'s client libraries use it (in tests).

But to be fair, `tdigest` is quite on the bottom of my priority list of packages.

**Comment by tchoutri** [comment]
A bit late to the party but we also provide a ClientM instance for Alt. Should it be removed? https://github.com/haskell-servant/servant/blob/master/servant-client/src/Servant/Client/Internal/HttpClient.hs#L152-L153

**Comment by phadej** [comment]
@tchoutri this is not a right place to ask that question

**Comment by phadej** [comment]
I check, `servant-client` doesn't even use `tdigest` for anything. The test which used it is commented out.

The test in question was trying to check that streaming can be done in bounded space. I guess it was fragile.

And `http-streams` don't even have mentions of `TDigest` modules, it's just there as unused test-dependency.

**Comment by Bodigrim** [comment]
Got the same issue with `semigroupoids-6` (and also `base-compat-0.13`, `vector-0.13` and `vector-algorithms-0.9`), because `tdigest` is a dependency of `numhask-space`, which is a dependency of `chart-svg`. 

I ran `cabal test -c 'base-compat>=0.13' -c 'vector>=0.13' -c 'vector-algorithms>=0.9' -c 'base-compat>=0.13' --allow-newer -w ghc-9.6`, so a revision should be enough.

**Comment by phadej** [comment]
There is https://hackage.haskell.org/package/tdigest-0.3
